task_name: learn_to_rank_lightgbm_regression
jobs:
  data:
    split_by_qid: false
  model:
    name: learn_to_rank_lightgbm_regression
    save_onnx: true
    params:
      task: train
      boosting: gbdt
      objective: regression
      num_leaves: 10
      learning_rate: 0.01
      feature_fraction: 0.5
      max_depth: -1
      num_iterations: 1000000
      num_threads: 0
      seed: 1234
      early_stopping_rounds: 10
      eval_metrics: mse
      verbose_eval: 10
