task_name: learn_to_rank_lightgbm_ranker
jobs:
  data:
    split_by_qid: true
  model:
    name: learn_to_rank_lightgbm_ranker
    save_onnx: false
    params:
      task: train
      objective: lambdarank
      metric: ndcg
      lambdarank_truncation_level: 10
      n_estimators: 10000
      boosting_type: gbdt
      num_leaves: 50
      learning_rate: 0.1
      max_depth: -1
      num_iterations: 10000
      num_threads: 0
      seed: 1234
      early_stopping_rounds: 5
      eval_metrics: ndcg
      verbose_eval: 1
