apiVersion: apps/v1
kind: Deployment
metadata:
  name: no-animal-violation-serving
  namespace: violation-detection
  labels:
    app: no-animal-violation-serving
spec:
  replicas: 2
  selector:
    matchLabels:
      app: no-animal-violation-serving
  template:
    metadata:
      labels:
        app: no-animal-violation-serving
    spec:
      initContainers:
        - name: model-loader
          image: shibui/building-ml-system:ai_animals_model_loader_0.0.0
          imagePullPolicy: Always
          command:
            - "python"
            - "-m"
            - "src.main"
          env:
            - name: MLFLOW_TRACKING_URI
              value: http://mlflow.mlflow.svc.cluster.local:5000
            - name: MLFLOW_PARAM_JSON
              value: "{}"
            - name: TARGET_ARTIFACTS
              value: "saved_model"
            - name: TARGET_URLS
              value: "https://storage.googleapis.com/aianimals/models/violation_detection/no_animal_violation_detection/saved_model.zip"
            - name: TARGET_DIRECTORY
              value: "/models/no_animal_violation/"
          volumeMounts:
            - mountPath: /models/no_animal_violation/
              name: data
      containers:
        - name: no-animal-violation-serving
          image: shibui/building-ml-system:ai_animals_violation_detection_no_animal_violation_serving_0.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8500
            - containerPort: 8501
          resources:
            limits:
              cpu: 1000m
              memory: "1000Mi"
            requests:
              cpu: 1000m
              memory: "1000Mi"
          env:
            - name: REST_API_PORT
              value: "8501"
            - name: PORT
              value: "8500"
          volumeMounts:
            - mountPath: /models/no_animal_violation/
              name: data
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: no-animal-violation-serving
  namespace: violation-detection
  labels:
    app: no-animal-violation-serving
spec:
  ports:
    - name: grpc
      port: 8500
      protocol: TCP
    - name: rest
      port: 8501
      protocol: TCP
  selector:
    app: no-animal-violation-serving
