task_name: violation_detection_no_animal_violation_detection
dataset:
  train:
    negative_file: /opt/data/train_animal.txt
    positive_file: /opt/data/train_no_animal.txt
  test:
    negative_file: /opt/data/test_animal.txt
    positive_file: /opt/data/test_no_animal.txt
  image:
    height: 224
    width: 224
  bucket: aianimals

jobs:
  train:
    model_name: mobilenet_v3
    tfhub_url: "https://tfhub.dev/google/imagenet/mobilenet_v3_large_100_224/classification/5"
    train_tfhub: true
    batch_size: 32
    epochs: 3
    learning_rate: 0.0005
    loss: categorical_crossentropy
    metrics:
      - acc
    threshold: 0.5
    augmentation:
      rotation_range: 10
      horizontal_flip: True
      height_shift_range: 0.2
      width_shift_range: 0.2
      zoom_range: 0.2
      channel_shift_range: 0.2
    callback:
      checkpoint: true
      early_stopping: true
      tensorboard: true
    save_as:
      saved_model: true
      tflite: true
