apiVersion: batch/v1
kind: Job
metadata:
  name: initial-data-registration
  namespace: beverage-sales-forecasting
  labels:
    app: initial-data-registration
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: init
          image: shibui/building-ml-system:beverage_sales_forecasting_data_registration_1.0.0
          imagePullPolicy: Always
          command:
            - bash
            - -c
            - |
              mkdir -p /opt/data/
              wget https://storage.googleapis.com/beverage_sales_forecasting/data/create.sql -P /opt/data/
              wget https://storage.googleapis.com/beverage_sales_forecasting/data/item_prices.csv -P /opt/data/
              wget https://storage.googleapis.com/beverage_sales_forecasting/data/items.csv -P /opt/data/
              wget https://storage.googleapis.com/beverage_sales_forecasting/data/regions.csv -P /opt/data/
              wget https://storage.googleapis.com/beverage_sales_forecasting/data/stores.csv -P /opt/data/
              wget https://storage.googleapis.com/beverage_sales_forecasting/data/item_sale_records_201701_202106.csv -P /opt/data/
          volumeMounts:
            - mountPath: /opt/data/
              name: data
      containers:
        - name: initial-data-registration
          image: shibui/building-ml-system:beverage_sales_forecasting_data_registration_1.0.0
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: "1000Mi"
            requests:
              cpu: 1000m
              memory: "1000Mi"
          command:
            - "python"
            - "-m"
            - "src.main"
            - "--init_sql_file_path"
            - "/opt/data/create.sql"
            - "--region_store_file_paths"
            - "/opt/data/regions.csv"
            - "/opt/data/stores.csv"
            - "--item_file_paths"
            - "/opt/data/items.csv"
            - "/opt/data/item_prices.csv"
            - "--item_sales_records_path"
            - "/opt/data/item_sale_records_201701_202106.csv"
          env:
            - name: POSTGRESQL_HOST
              value: postgres.data.svc.cluster.local
            - name: POSTGRESQL_PORT
              value: "5432"
            - name: POSTGRESQL_USER
              value: postgres
            - name: POSTGRESQL_PASSWORD
              value: password
            - name: POSTGRESQL_DBNAME
              value: beverage_sales_forecasting
          volumeMounts:
            - mountPath: /opt/data/
              name: data
      volumes:
        - name: data
          emptyDir: {}
