[tool.poetry]
name = "model_loader"
version = "0.0.0"
description = ""
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.10.6"
click = "^8.0.4"
SQLAlchemy = "^1.4.32"
psycopg2-binary = "^2.9.3"
mlflow = "^1.24.0"
httpx = "^0.23.0"
dependency-injector = "^4.39.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
