ARG FROM_IMAGE=python:3.9-slim

FROM ${FROM_IMAGE}

ENV PROJECT_DIR opt
WORKDIR /${PROJECT_DIR}
RUN pip install mlflow

CMD [ "mlflow", "server", "--backend-store-uri", "/opt/outputs/mlruns", "--default-artifact-root", "/opt/outputs/mlruns", "--host", "0.0.0.0" ]
