apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: event-exporter-gke
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: event-exporter

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: konnectivity-agent
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: konnectivity-agent

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-dns-autoscaler
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns-autoscaler

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kube-dns
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: kube-dns

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: glbc
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: glbc

---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      k8s-app: metrics-server
